
name: Compile Latex and Release PDF  
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
    
jobs:
  
  build_latex:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Get Current Date
        id: get_current_date
        uses: josStorer/get-current-time@v2
        with:
          format: YYYYMMDD-HH
          utcOffset: "-04:00"

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            en.tex
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}
          
      - name: Rename PDF's
        run: mv en.pdf cv_${{ steps.get_current_date.outputs.formattedTime }}_en.pdf
      
      - name: Tagged Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.get_current_date.outputs.formattedTime }}
          prerelease: false
          files: |
            *.pdf

      